services:
  db:
    container_name: fishstore-db
    image: mysql:8.4
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=fishstore
    volumes:
      - './docker/mysql:/var/lib/mysql'
